// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl4qUDS_Z7jVooEVl9ZQ2JsRyt5FHmAaM',
    appId: '1:805946824847:web:c37225fe655797a040b8fa',
    messagingSenderId: '805946824847',
    projectId: 'fir-memo-app-593c2',
    authDomain: 'fir-memo-app-593c2.firebaseapp.com',
    storageBucket: 'fir-memo-app-593c2.appspot.com',
    measurementId: 'G-PX4EKGWX79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqza-sZuBBw_Mxq9uNVRgsoCLG-lQWVqA',
    appId: '1:805946824847:android:68ff760155c78f1240b8fa',
    messagingSenderId: '805946824847',
    projectId: 'fir-memo-app-593c2',
    storageBucket: 'fir-memo-app-593c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDXcZ42oz-CkxtRoWMV2mxS-N8SMZPIKM',
    appId: '1:805946824847:ios:03e6a416228edf7d40b8fa',
    messagingSenderId: '805946824847',
    projectId: 'fir-memo-app-593c2',
    storageBucket: 'fir-memo-app-593c2.appspot.com',
    iosBundleId: 'com.example.udemyFirebaseMemo',
  );
}
